### PR TITLE
[WIP] 2023.11

### PR DESCRIPTION
**Pull request by milouse**

### CODE REVIEW

**Comment by milouse** [comment]
@philipp-classen later this week I’ll rebase this MR on latest master. I was waiting for the next stable release to merge it with it, but maybe it’s not an issue to still merge in master without a real new package version? Or we can wait for the next stable?

**Comment by philipp-classen** [comment]
> @philipp-classen later this week I’ll rebase this MR on latest master. I was waiting for the next stable release to merge it with it, but maybe it’s not an issue to still merge in master without a real new package version? Or we can wait for the next stable?

There should a bugfix release coming soon (fixing broken locales). Though I think, it would not be a problem to decouple pull requests from releases.

**Comment by philipp-classen** [comment]
FYI: I cherry-picked the changes here into the PR for the bugfix release:
https://github.com/flathub/com.ghostery.browser/pull/18

**Comment by philipp-classen** [comment]
Closing this one now, because the commits here are now on master (via https://github.com/flathub/com.ghostery.browser/pull/18)

**Pull request closed without merging**
